language: node_js
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14

script: npm test

matrix:
  include:
  - name: "eslint"
    node_js: 12
    script: npm run lint
  - name: "test coverage"
    node_js: 12
    script: ./node_modules/.bin/jest --coverage
